# Generated by Django 5.1 on 2024-08-09 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerconnect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='careerconnect.country'),
        ),
    ]
