# Generated by Django 5.1 on 2024-08-09 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerconnect', '0002_alter_employee_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='job_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees_location', to='careerconnect.country'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees_country', to='careerconnect.country'),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='careerconnect.workplace'),
        ),
    ]
