# Generated by Django 5.1 on 2024-08-11 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerconnect', '0004_alter_employee_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPortal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
