# Generated by Django 5.1 on 2024-08-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerconnect', '0007_searchquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='non_tech',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='remote',
            field=models.BooleanField(default=False),
        ),
    ]
