# Generated by Django 5.1 on 2024-08-23 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerconnect', '0010_alter_company_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisaOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(max_length=255, unique=True)),
                ('link_1', models.URLField(max_length=255, unique=True)),
                ('link_2', models.URLField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visa_country', to='careerconnect.country')),
            ],
        ),
    ]
