# Generated by Django 5.1 on 2024-08-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerconnect', '0011_visaopportunity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visaopportunity',
            name='link_1',
            field=models.URLField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='visaopportunity',
            name='link_2',
            field=models.URLField(max_length=255, null=True, unique=True),
        ),
    ]
