# Generated by Django 5.1 on 2024-08-23 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerconnect', '0012_alter_visaopportunity_link_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visaopportunity',
            name='link_1',
            field=models.URLField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='visaopportunity',
            name='link_2',
            field=models.URLField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
