# Generated by Django 5.1.1 on 2024-09-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerconnect', '0013_alter_visaopportunity_link_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='is_employee_checked',
            field=models.BooleanField(default=False),
        ),
    ]
