# Generated by Django 5.1.1 on 2024-09-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerconnect', '0014_company_is_applied_company_is_employee_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='target',
            field=models.BooleanField(default=False),
        ),
    ]
