# Generated by Django 5.1.1 on 2024-09-14 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerconnect', '0015_employee_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobportal',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='careerconnect.country'),
        ),
        migrations.AddField(
            model_name='jobportal',
            name='is_remote',
            field=models.BooleanField(default=False),
        ),
    ]
